spring:
    data:
        mongodb:
            uri: mongodb+srv://chinmaykhiste2006_db_user:Chinmay_mongo_pass@cluster01c.hibgdkh.mongodb.net
            database: journaldb
            auto-index-creation: true
 
    redis:
      host: redis-18447.crce263.ap-south-1-1.ec2.cloud.redislabs.com
      port: 18447
      password: v8tK7nqUxQgMLcwsuxsDQ7nS4bbSDWVF
 

    mail:
        host: smtp.gmail.com
        port: 587
        username: chinmay.khiste241@vit.edu
        password: dolt xmdq rujx hquz
        properties: 
            mail:
                smtp: 
                    auth: true
                    starttls: 
                        enable: true        

server:
    port: 8081
    servlet:
        context-path: /journal