spring:
    data:
        mongodb:
            uri: mongodb+srv://chinmaykhiste2006_db_user:Chinmay_mongo_pass@cluster01c.hibgdkh.mongodb.net
            database: journaldb
            auto-index-creation: true

server:
    port: 8081
    servlet:
        context-path: /journal